import "./globals.css";
import { Noto_Sans_KR } from "next/font/google";
import Provider from "./Provider";
import Header from "@/layouts/header/Header";
import Footer from "@/layouts/footer/Footer";

const NotoSansKR = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["700", "500", "400", "300"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={NotoSansKR.className}>
        <Provider>
          <Header />
          <section className="contents">{children}</section>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
